# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_buy', models.DateTimeField()),
                ('summa_buy', models.DecimalField(decimal_places=2, max_digits=9)),
                ('note', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Incomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_income', models.DateTimeField()),
                ('summa_income', models.DecimalField(decimal_places=2, max_digits=9)),
                ('note', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Typeofbuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeofbuy_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Typeofincome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeofincome_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='incomes',
            name='type_of_income',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.Typeofincome'),
        ),
        migrations.AddField(
            model_name='costs',
            name='type_of_buy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.Typeofbuy'),
        ),
    ]
