# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-23 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='date_buy',
            field=models.DateTimeField(help_text='гггг-мм-дд', verbose_name='Дата покупки'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='note',
            field=models.CharField(max_length=200, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='summa_buy',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Сумма покупки'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='type_of_buy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.Typeofbuy', verbose_name='Тип покупки'),
        ),
        migrations.AlterField(
            model_name='typeofbuy',
            name='typeofbuy_text',
            field=models.CharField(max_length=200, verbose_name='Тип покупки'),
        ),
    ]
