# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20170723_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costs',
            options={'ordering': ['-date_buy']},
        ),
        migrations.AlterField(
            model_name='costs',
            name='note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Примечание'),
        ),
    ]
